### ISSUE TITLE
Example.ConcatTest: Compiler failed to build request fatal error: Unable to create pipeline state, check metal shaders: file

### ISSUE THREAD

**Issue by samkohli** [xmartlabs/Bender#38] opened 2017-07-10 23:12 UTC
Environment: Xcode: Version 8.3.3 (8E3004b)
                       iOS:  10.3
                       Device: iPhone 6 Plus

             

Stacktrace:

2017-07-10 18:54:19.618344-0400 Example[1174:306198] [DYMTLInitPlatform] platform initialization successful
2017-07-10 18:54:19.753218-0400 Example[1174:305990] Metal GPU Frame Capture Enabled
2017-07-10 18:54:19.754074-0400 Example[1174:305990] Metal API Validation Enabled
2017-07-10 18:54:19.808660-0400 Example[1174:305990] libMobileGestalt MobileGestaltSupport.m:153: pid 1174 (Example) does not have sandbox access for frZQaeyWLUvLjeuEK43hmg and IS NOT appropriately entitled
2017-07-10 18:54:19.808771-0400 Example[1174:305990] libMobileGestalt MobileGestalt.c:550: no access to InverseDeviceID (see <rdar://problem/11744455>)
Running test: Example.TextureConversionTest
Running test: Example.LocalResponseNormTest
Running test: Example.InstanceNormTest
Running test: Example.ConcatTest
2017-07-10 18:54:20.203515-0400 Example[1174:306178] Compiler failed to build request
fatal error: Unable to create pipeline state, check metal shaders: file /LATEST_RESEARCH/LATEST/Bender/Sources/Core/MetalShaderManager.swift, line 61
2017-07-10 18:54:20.205110-0400 Example[1174:305990] fatal error: Unable to create pipeline state, check metal shaders: file /LATEST_RESEARCH/LATEST/Bender/Sources/Core/MetalShaderManager.swift, line 61

**Comment by PetroWu** [comment] 2017-07-12 05:40
I have the same issue in the example code without any modification. Any help?

**Comment by AndreJFBico** [comment] 2017-07-13 10:39
Same issue.

**Comment by bryant1410** [comment] 2017-07-13 16:08
It seems that it found the "concat_x" kernel in the test but fails to create the pipeline state for some reason.

This works fine on iphone 7 and 6s with the same Xcode and iOS versions. So it seems to be a problem with iphone 6.

Researching further, concat is the only one that uses "arrays". And according to the [Metal Feature Set Table](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf), an array of textures is unavailable in iOS 10 for GPU families prior to 3. iphone 6 uses A8 which has a version 2 of the GPU family, in contrast with the A9 and A10 of iphone 6s and 7 which have version 3. So the problem is the lack of support for array of textures in iphone 6 devices.

We will see what we can do about this and write again soon.

**Comment by dernster** [comment] 2017-07-13 22:43
Hey @samkohli @PetroWu @AndreJFBico I've just created a pull request for this. In the meantime you can try pointing to this [branch](https://github.com/xmartlabs/Bender/tree/fix/issue-38) and let me know if it helps.

**Comment by AndreJFBico** [comment] 2017-07-14 09:07
@dernster i tested on a 6 plus and all tests now pass with that fix.

**Comment by AndreJFBico** [comment] 2017-07-16 21:47
However the style transfer example shows a brown image, it runs successfully but the result is just brown.

**Comment by bryant1410** [comment] 2017-07-16 22:16
on iphone 6 in that branch? what about master?

**Comment by AndreJFBico** [comment] 2017-07-16 22:35
It happens on iphone 6 with the pull request branch.

This is the console output:
`ALL TEST PASSED
"Unknown input: ^moments/sufficient_statistics/mean_ss"
"Unknown input: ^moments/sufficient_statistics/var_ss"
"Unknown input: ^moments_1/sufficient_statistics/mean_ss"
"Unknown input: ^moments_1/sufficient_statistics/var_ss"
"Unknown input: ^moments_2/sufficient_statistics/mean_ss"
"Unknown input: ^moments_2/sufficient_statistics/var_ss"
"Unknown input: ^moments_3/sufficient_statistics/mean_ss"
"Unknown input: ^moments_3/sufficient_statistics/var_ss"
"Unknown input: ^moments_4/sufficient_statistics/mean_ss"
"Unknown input: ^moments_4/sufficient_statistics/var_ss"
"Unknown input: ^moments_5/sufficient_statistics/mean_ss"
"Unknown input: ^moments_5/sufficient_statistics/var_ss"
"Unknown input: ^moments_6/sufficient_statistics/mean_ss"
"Unknown input: ^moments_6/sufficient_statistics/var_ss"
"Unknown input: ^moments_7/sufficient_statistics/mean_ss"
"Unknown input: ^moments_7/sufficient_statistics/var_ss"
"Unknown input: ^moments_8/sufficient_statistics/mean_ss"
"Unknown input: ^moments_8/sufficient_statistics/var_ss"
"Unknown input: ^moments_9/sufficient_statistics/mean_ss"
"Unknown input: ^moments_9/sufficient_statistics/var_ss"
"Unknown input: ^moments_10/sufficient_statistics/mean_ss"
"Unknown input: ^moments_10/sufficient_statistics/var_ss"
"Unknown input: ^moments_11/sufficient_statistics/mean_ss"
"Unknown input: ^moments_11/sufficient_statistics/var_ss"
"Unknown input: ^moments_12/sufficient_statistics/mean_ss"
"Unknown input: ^moments_12/sufficient_statistics/var_ss"
"Unknown input: ^moments_13/sufficient_statistics/mean_ss"
"Unknown input: ^moments_13/sufficient_statistics/var_ss"
"Set up takes:: 1.77025699615479 (0.564889731927128 per second)"`

Screenshot of the example after clicking run of course:
http://imgur.com/a/WIUHE

When testing the master branch it fails the tests, which is fixed by the pull request branch. Now if i comment "testRunner.run" in ViewController.swift and run the fast style transfer the problem still occurs.

**Comment by dernster** [comment] 2017-07-17 12:19
@AndreJFBico Thanks for reporting this! On iPhone 7 is working fine so it seems to be a problem with iPhone 6... I'm not able to test it until Wednesday though. Can you please open another issue related to just the brown image? Since the pull request will be closing the initial issue of the Concat. Thanks!

**Closed** 2017-07-17 12:25 UTC

**Comment by AndreJFBico** [comment] 2017-07-17 13:44
Hey i just realised i was testing it with iOS 11 i can confirm it is working with iOS 10, sorry for the confusion.
